### ISSUE TITLE
Server becomes unresponsive if bad video uploaded

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#10]
Burnerboard Brain goes whacky when a video is uploaded with bad content

**Comment by danielkeithw** [comment]
also a bad audio.  Symptoms:

Power on brain and lights
watch battery pattern - NORMAL
colored matrix pattern - NORMAL
music - NORMAL
wait 60 seconds..  NORMAL
pattern 'stalls' for an instant
60 seconds
pattern repeatedly stalls
pattern freeze
music stops
30 seconds FROZEN
pattern restarts
music restarts
wait 60 seconds .. NORMAL
pattern freeze
music freeze
wait 30 seconds
pattern restart
music restart
the symptoms appear to be constant restarts of the brain software

This happened after i uploaded a 60BMP file.

**Comment by danielkeithw** [comment]
my symptoms required a reflash of android.

**Comment by danielkeithw** [comment]
this has not reproduced in quite some time.
