### ISSUE TITLE
Visualization service crashing / race condition.

### ISSUE THREAD

**Issue by danielkeithw** [rjmcdougall/BB#107]
With the latest build...       

mode is 0 (after += -1).  GetVideo(mode) is returning null.   The .has("algorithm") is throwing exceptions.  This allows the code to proceed, but I'm not sure what the underlying issue is.

 // TODO: check perf overhead of checking this every frame
        if(mBurnerBoard.mBBService.dlManager.GetVideo(mode) != null) {
            if (mBurnerBoard.mBBService.dlManager.GetVideo(mode).has("algorithm")) {
                String algorithm = mBurnerBoard.mBBService.dlManager.GetAlgorithm(mode);
                return displayAlgorithm(algorithm);
            } else {
                mVisualizationVideo.update(mode);
                return mFrameRate;
            }
        }
        else
            return mFrameRate;

**Comment by danielkeithw** [comment]
if(mBurnerBoard.mBBService.dlManager.dataDirectory == null){
            return mFrameRate;
        }

This happens if the directory is not loaded when this method gets hit. fix is return if the directory is null

**Comment by rjmcdougall** [comment]
Crashed on Cranky with blank profile after fix.
