### ISSUE TITLE
Disable visuals via the app

### ISSUE THREAD

**Issue by jib** [rjmcdougall/BB#110]
Backpacks don't use visuals, and visuals are battery intensive. Can we get an option in the BB App to disable visuals? It would probably mean toggling this setting:

https://github.com/rjmcdougall/BB/blob/03e4295ea3cf6a26fcc7fd4e4833ddf378831cdd/bb/src/main/java/com/richardmcdougall/bb/BoardVisualization.java#L129

**Comment by danielkeithw** [comment]
@jib  do you still want this?
