### ISSUE TITLE
Android Things (& Rasberry Pi) needs additional permissions file for installer to work

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#124]
In 8.0+/Android Things, additional permissions are needed to allow installer to update bb package as root.

/etc/permissions/privapp-permissions-com.richardmcdougall.bb.xml:

<?xml version="1.0" encoding="utf-8"?>
<permissions>
    <permission name="android.permission.INTERACT_ACROSS_USERS_FULL" />
</permissions>

We'll need to add this to the adb installer-installer script

**Comment by jib** [comment]
@rjmcdougall which permissions are these? point & grunt in the right direction and I'll take a crack at it

**Comment by rjmcdougall** [comment]
not using this installer on rpi now (using android things installer)
