### ISSUE TITLE
Board says aloud an error

### ISSUE THREAD

**Issue by edfine** [rjmcdougall/BB#125]
Pegasus is saying an error aloud over the track she is playing.  
"unterminated object at ....Version 3800..." 

Steps to reproduce, turn Pegasus on.  
Relevant notes from app diagnostic page.  APK version 3805, BLE:Read APK VersionValue: 3805

**Comment by rjmcdougall** [comment]
Root cause was an error in the cloud DownloadApp.json for the upgrader.
