### ISSUE TITLE
Hardware problem with Vega's battery wiring

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#133]
I suspect there is a loose wire -- seems to work great when it's not being ridden -- possibly suffers from vibrating from what I can see.

**Comment by rjmcdougall** [comment]
Also seeing this on Monaco.

Observed behavior:

- %age goes between accurate and zero
- Voltage jumps to 43200 volts temporarily

I suspect this to be a hardware issue with the battery board. It happened permanently on pegasus's battery board once and a replacement fixed it. The two suspect boards are also covered in playa dust.

Further hardware diagnostic required.

**Comment by rjmcdougall** [comment]
Lets replace the battery computer and reprovision.

**Comment by danielkeithw** [comment]
ed fixed this.
