### ISSUE TITLE
Tracks start in the middle

### ISSUE THREAD

**Issue by lesliefine** [rjmcdougall/BB#134]
Added "Sunday Riding" to "test_sync." Media update no problem. Track starts 2/3 of the way through. Sure would be nice to be able to restart tracks! @danielkeithw

**Comment by rjmcdougall** [comment]
That's violating a fundamental design constraint -- to make the music syncable they all must play at a predetermined offset which is only linked to time. You can't restart a track at all.

**Comment by danielkeithw** [comment]
@rjmcdougall thats true when syncing, but when a board is disconnected from syncing is it?

**Comment by rjmcdougall** [comment]
@danielkeithw when is a board disconnected? It's always part of the sync.

**Comment by danielkeithw** [comment]
wont fix
