### ISSUE TITLE
Akula is not updating battery

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#152]
Likely because MQTT backed up because wifi was offline since Jul 3.

Need to test changing MQTT option to delete oldest messages.

For Akula; just clearing out the MQTT files will reset it.

**Comment by woodsonmartin** [comment]
How can I clear out the MQTT files?

**Comment by rjmcdougall** [comment]
Wifi had no password; manually connected.

Also MQTT overflowed. 

Closing this since we have MQTT bug open - requires a fix otherwise boards will not be happy when no WIFI.
