### ISSUE TITLE
Pegasus is not reporting to Bigquery and not showing up in the app

### ISSUE THREAD

**Issue by edfine** [rjmcdougall/BB#167]
Pegasus does not show up in the bq table and has not since 7/22/2018.  Only 9 boards show up.  It does show up on the Burnerboard app via bluetooth.

**Comment by edfine** [comment]
No I don't, but I can bring it tomorrow or Thursday.

**Comment by lesliefine** [comment]
Is this still happening, @edfine?

**Comment by danielkeithw** [comment]
i can see it now
