### ISSUE TITLE
 Rename JosPack only algos: append with “pack” or similar

### ISSUE THREAD

**Issue by lesliefine** [rjmcdougall/BB#182]
We are going to have one master profile, so it needs to be easy to know which algorithms which device can use.

**Comment by jib** [comment]
All algorithms are already prefixed with "JP" and are in their own class in the code base. We can rename the 'Pretty Name' for algorithms in the UI if that's what you're asking.

**Comment by jib** [comment]
ALso, we're not doing a master profile, we're doing 2 profiles with shared music files.
