### ISSUE TITLE
JosPack 2018 causes Azul boards to stop responding to the app via bluetooth 

### ISSUE THREAD

**Issue by edfine** [rjmcdougall/BB#210]
Simply turning on a pack in bluetooth range of an Azul board causes the board to stop being available to the app.  Music and lights continue.  Turning the pack off and rebooting the brain allows it to be discoverable again.  
I have not tested the Satechi.  

Steps to reproduce: 
Turn on Azul board (e.g. Pegasus) and connect with app.
Turn on un-updated JosPack (Statler) with the build from 2018 burn.

Expected: 
Be able to see the Azul board with the app and connect with no effect from the JosPack.
Observed:  
Note that the board is
![IMG_1654](https://user-images.githubusercontent.com/744421/61686137-a5b9b980-acd3-11e9-8511-97626ec3da1c.PNG)
![IMG_1655](https://user-images.githubusercontent.com/744421/61686145-a94d4080-acd3-11e9-9e42-7b4b0b2f2fd1.JPG)
![IMG_1657](https://user-images.githubusercontent.com/744421/61686164-b23e1200-acd3-11e9-8f27-9c77176ff236.PNG)
![IMG_1659](https://user-images.githubusercontent.com/744421/61686175-b79b5c80-acd3-11e9-960c-1ee6eddb298c.JPG)
![IMG_1658](https://user-images.githubusercontent.com/744421/61686181-bd913d80-acd3-11e9-9e28-9088905e3527.PNG)

 no longer connected and the board is no longer discoverable.

**Comment by edfine** [comment]
@danielkeithw @rjmcdougall This is the JosPack bug.  
Perhaps we could work around by updating all JosPacks, but it may be better to figure out what's up with the Azul Brain.

**Comment by danielkeithw** [comment]
I think it may be with the app and not the azul Brain. Thank you I’ll take
a look!

**Comment by danielkeithw** [comment]
deprecating rpi
