### ISSUE TITLE
Playa 2019 Audio is Skipping like Crazy

### ISSUE THREAD

**Issue by danielkeithw** [rjmcdougall/BB#219]
Seems to be caused by being mastered via a board that has its clock set incorrectly.  

The solution to this appears to be to hand crank the time from 1970 back out to current day.

can we use the GPS time?

**Comment by rjmcdougall** [comment]
We didn't fix this though, right?

We need to find out why 1970 doesn't work (it should).

**Comment by danielkeithw** [comment]
97489d0
