### ISSUE TITLE
Grumpy thinks it's supersexy.

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#236]
03-30 03:48:26.739  1924  1924 I BB.BBService: onCreate
03-30 03:48:26.739  1924  1924 I BB.BBService: Current Clock: 27895
03-30 03:48:26.739  1924  1924 I BB.BBService: startElapsedTime: 0
03-30 03:48:26.739  1924  1924 I BB.BBService: Build Manufacturer FriendlyELEC (www.friendlyarm.com)
03-30 03:48:26.739  1924  1924 I BB.BBService: Build Model NanoPC-T4 (RK3399)
03-30 03:48:26.739  1924  1924 I BB.BBService: Build Serial SWRO7G27AH
03-30 03:48:26.742  1924  1924 D BB.AllBoards: Dir [{"color":"cornsilk","address":16,"isProfileGlobal":true,"profile":"MVC2019","name":"DigitalMast","videoContrastMultiplier":1,"type":"mast","bootName":"DigitalMast","isActive":true},{"videoContrastMultiplier":3,"type":"azul","color":"indianred","targetAPKVersion":"5029","address":1,"isProfileGlobal":true,"profile":"MVC2019","name":"akula","isProfileGlobal2":true,"bootName":"akula","isActive":true,"profile2":"DKW Test"},{"isProfileGlobal":true,"profile":"MVC2019","name":"artemis","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"artemis","isActive":true,"profile2":"MVC2018","color":"gray","address":5},{"profile2":"MVC2018","color":"yellow","address":6,"isProfileGlobal":true,"profile":"MVC2019","name":"biscuit","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"biscuit","isActive":true},{"profile":"MVC2019","name":"boadie","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"boadie","isActive":true,"profile2":"MVC2018","color":"gold","address":14,"isProfileGlobal":true},{"type":"boombox","bootName":"boomi","isActive":true,"color":"lightblue","address":3,"isProfileGlobal":true,"profile":"MVC2019","name":"boomi","videoContrastMultiplier":1,"isProfileGlobal2":false},{"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy4","color":"hotpink","address":2,"isProfileGlobal":true,"profile":"MVC2019","name":"candy","isProfileGlobal2":true,"bootName":"candy","isActive":true,"profile2":"MVC2018"},{"color":"moccasin","address":4,"isProfileGlobal":true,"profile":"MVC2018","name":"cranky","videoContrastMultiplier":3,"type":"panel","bootName":"cranky","isActive":true},{"address":13,"isProfileGlobal":true,"profile":"MVC2019","name":"goofy","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"goofy","isActive":true,"profile2":"MVC2018","color":"green"},{"name":"grumpy","isProfileGlobal2":false,"bootName":"npiTEMWE","isActive":true,"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy4","color":"green","targetAPKVersion":5029,"address":15,"isProfileGlobal":true,"profile":"MVC2019"},{"isProfileGlobal":true,"profile":"MVC2019","name":"joon","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"joon","isActive":true,"profile2":"MVC2018","color":"yellow","address":9},{"color":"palegreen","address":7,"isProfileGlobal":true,"profile":"MVC2019","name":"monaco","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"monaco","isActive":true,"profile2":"MVC2019"},{"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy3","color":"black","targetAPKVersion":"5029","address":18,"isProfileGlobal":true,"profile":"MVC2019","name":"newbie","isProfileGlobal2":false,"bootName":"npiSRMHN","isActive":true},{"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy3","color":"black","targetAPKVersion":"5029","address":17,"isProfileGlobal":true,"profile":"MVC2019","name":"newbie","isProfileGlobal2":false,"bootName":"npi3HWBX","isActive":true},{"color":"purple","address":8,"isProfileGlobal":true,"profile":"MVC2019","name":"pegasus","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"pegasus","isActive":true,"profile2":"MVC2019"},{"isProfileGlobal":true,"profile":"MVC2019","name":"ratchet","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"ratchet","isActive":true,"profile2":"MVC2018","color":"orange","address":10},{"profile":"MVC2019","name":"squeeze","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"squeeze","isActive":true,"profile2":"MVC2018","color":"red","address":11,"isProfileGlobal":true},{"videoContrastMultiplier":3,"type":"panel","displayTeensy":"teensy3","color":"steelblue","targetAPKVersion":"5029","address":12,"isProfileGlobal":true,"profile":"MVC2019","name":"supersexy","isProfileGlobal2":false,"bootName":"npiG27AH","isActive":true}]
03-30 03:48:26.743  1924  1924 D BB.AllBoards: Found bootName: npiG27AH
03-30 03:48:26.743  1924  1924 D BB.AllBoards: Found publicName: supersexy
03-30 03:48:26.743  1924  1924 D BB.AllBoards: Address 12
03-30 03:48:26.744  1924  1924 D BB.AllBoards: Board Type panel
03-30 03:48:26.744  1924  1924 D BB.AllBoards: Target APK Version 5029
03-30 03:48:26.744  1924  1924 D BB.AllBoards: videoContrastMultiplier 3
03-30 03:48:26.744  1924  1924 D BB.BoardState: contents of wifi.json: {"SSID":"burnerboard","password":"firetruck"}
03-30 03:48:26.778  1924  1924 D BB.BBWifi: Wifi SSIDs"burnerboard" "burnerboard"
03-30 03:48:26.779  1924  1924 D BB.BBWifi: WIFI IP Address: 10.0.6.198
03-30 03:48:26.780  1924  1924 D BB.BBWifi: Enable WiFi reconnect? true
03-30 03:48:26.781  1924  1924 I BB.BBService: State Version 5029
03-30 03:48:26.786  1924  1924 I BB.BBService: State APK Updated Date Sun Mar 29 23:54:18 GMT+00:00 2020
03-30 03:48:26.787  1924  1924 I BB.BBService: State Address 12
03-30 03:48:26.787  1924  1924 I BB.BBService: State SSID burnerboard
03-30 03:48:26.787  1924  1924 I BB.BBService: State Password firetruck
03-30 03:48:26.787  1924  1924 I BB.BBService: State Mode 0
03-30 03:48:26.787  1924  1924 I BB.BBService: State BOARD_ID supersexy
03-30 03:48:26.787  1924  1924 I BB.BBService: State Tyoe panel
03-30 03:48:26.787  1924  1924 I BB.BBService: Display Teensy teensy3
03-30 03:48:26.787  1924  1924 I BB.BBService: Video Contrast Multiplier  3
03-30 03:48:26.789  1924  1924 D BB.IoTClient: Creating MQTT Client
03-30 03:48:26.789  1924  1924 D BB.IoTClient: connect(google, projects/burner-board/locations/us-central1/registries/bb-registry/devices/bb-supersexy)
03-30 03:48:26.794  1924  1924 D BB.MediaManager: Downloading files to: /data/user/0/com.richardmcdougall.bb/files
03-30 03:48:26.794  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:28.794  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:28.964  1902  1902 I BB.BBWifi: wifi scan results[SSID: CBCI-C647-2.4, BSSID: 84:00:2d:81:58:18, capabilities: [WPA2-PSK-CCMP+TKIP][WPA-PSK-CCMP+TKIP][ESS][WPS], level: -51, frequency: 2462, timestamp: 30073968, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: 825berkeley, BSSID: 78:8a:20:2a:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -52, frequency: 2412, timestamp: 30073860, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: burnerboard, BSSID: 7a:8a:20:2a:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -52, frequency: 2412, timestamp: 30073866, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: , BSSID: aa:8a:20:2a:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -52, frequency: 2412, timestamp: 30073901, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: rmcnet, BSSID: 9a:8a:20:2a:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -53, frequency: 2412, timestamp: 30073879, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: management, BSSID: 8a:8a:20:2a:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -53, frequency: 2412, timestamp: 30073873, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: CBCI-C647-5, BSSID: 84:00:2d:81:58:20, capabilities: [WPA2-PSK-CCMP+TKIP][WPA-PSK-CCMP+TKIP][ESS][WPS], level: -59, frequency: 5180, timestamp: 30074005, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 2, centerFreq0: 5210, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: xfinitywifi, BSSID: 84:00:2d:81:58:21, capabilities: [ESS], level: -59, frequency: 5180, timestamp: 30074012, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 2, centerFreq0: 5210, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: XFINITY, BSSID: 84:00:2d:81:58:22, capabilities: [WPA2-EAP-CCMP][ESS], level: -59, frequency: 5180, timestamp: 30074019, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 2, centerFreq0: 5210, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: burnerboard, BSSID: 7a:8a:20:2b:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -63, frequency: 5745, timestamp: 30073915, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 1, centerFreq0: 5755, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: management, BSSID: 8a:8a:20:2b:db:cd, capabilities: [WPA2-PSK-CCMP][ESS], level: -64, frequency: 5745, timestamp: 30074065, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 1, centerFreq0: 5755, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: rmcnet, BSSID: 96:83:c2:03:dd:9a, capabilities: [WPA2-PSK-CCMP][ESS], level: -74, frequency: 2437, timestamp: 30073929, distance: ?(cm), distanceSd: ?(cm), passpoint: no, ChannelBandwidth: 0, centerFreq0: 0, centerFreq1: 0, 80211mcResponder: is not supported, Carrier AP: no, Carrier AP EAP Type: -1, Carrier name: null, SSID: 825berkeley, BS
03-30 03:48:30.795  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:31.682  1902  1981 D BB.AllBoards: videoContrastMultiplier 3
03-30 03:48:31.689  1902  1985 I BB.BBWifi: Connected to "burnerboard"IP Address: 10.0.6.198
03-30 03:48:31.793  1924  2274 D BB.IoTClient: Disconnecting MQTT Client
03-30 03:48:31.794  1924  2274 D BB.IoTClient: Connecting MQTT Client
03-30 03:48:31.972  1924  2274 D BB.IoTClient: Created key eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODU1NDAxMTEsImV4cCI6MTU4NTU0MTMxMSwiYXVkIjoiYnVybmVyLWJvYXJkIn0.NMZ0D5vSo_-Se1NxR8jWvPTB8PxBtB1DTShrnUIQMDmQuNIxJvYOOmfDhIR9xFITNxxKacWNpEmvL_XF4-PEoCtJEbQlSURnSLwogRtPLg4cpiBsAEiEc2MiozhOdFI3NdjQMP9SIa4QkdKiCUJBARLilfZGBzMY94iQ9Yd5AuyAAxquRZIAFtkNUY_Na5I8-NMaMWAk1B0O2dqgCFS4UgO8rBWz_kstfBmvftD2Izcl935gP3uYG89cCLAGtg_wc9AwBClt_QnxQjswPwFPHMOjjksBeWK-bS4PrahztRAXehdtbO9n5jDxlp3m8uzJJwL_zYdmJznd1FPt8oCrhg
03-30 03:48:32.795  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:34.743  1924  2267 D BB.AllBoards: https://us-central1-burner-board.cloudfunctions.net/boards/
03-30 03:48:34.796  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:35.051  1924  2267 D BB.FileHelpers: Downloading https://us-central1-burner-board.cloudfunctions.net/boards/
03-30 03:48:35.055  1924  2267 D BB.AllBoards: Downloaded Boards JSON: [{"type":"mast","bootName":"DigitalMast","isActive":true,"color":"cornsilk","address":16,"isProfileGlobal":true,"profile":"MVC2019","name":"DigitalMast","videoContrastMultiplier":1},{"videoContrastMultiplier":3,"type":"azul","color":"indianred","targetAPKVersion":"5029","address":1,"isProfileGlobal":true,"profile":"MVC2019","name":"akula","isProfileGlobal2":true,"bootName":"akula","isActive":true,"profile2":"DKW Test"},{"address":5,"isProfileGlobal":true,"profile":"MVC2019","name":"artemis","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"artemis","isActive":true,"profile2":"MVC2018","color":"gray"},{"profile2":"MVC2018","color":"yellow","address":6,"isProfileGlobal":true,"profile":"MVC2019","name":"biscuit","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"biscuit","isActive":true},{"bootName":"boadie","isActive":true,"profile2":"MVC2018","color":"gold","address":14,"isProfileGlobal":true,"profile":"MVC2019","name":"boadie","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic"},{"type":"boombox","bootName":"boomi","isActive":true,"color":"lightblue","address":3,"isProfileGlobal":true,"profile":"MVC2019","name":"boomi","videoContrastMultiplier":1,"isProfileGlobal2":false},{"address":2,"isProfileGlobal":true,"profile":"MVC2019","name":"candy","isProfileGlobal2":true,"bootName":"candy","isActive":true,"profile2":"MVC2018","videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy4","color":"hotpink"},{"name":"cranky","videoContrastMultiplier":3,"type":"panel","bootName":"cranky","isActive":true,"color":"moccasin","address":4,"isProfileGlobal":true,"profile":"MVC2018"},{"isProfileGlobal":true,"profile":"MVC2019","name":"goofy","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"goofy","isActive":true,"profile2":"MVC2018","color":"green","address":13},{"isProfileGlobal2":false,"bootName":"npiTEMWE","isActive":true,"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy4","color":"green","targetAPKVersion":5029,"address":15,"isProfileGlobal":true,"profile":"MVC2019","name":"grumpy"},{"color":"yellow","address":9,"isProfileGlobal":true,"profile":"MVC2019","name":"joon","videoContrastMultiplier":1,"isProfileGlobal2":true,"type":"classic","bootName":"joon","isActive":true,"profile2":"MVC2018"},{"type":"azul","bootName":"monaco","isActive":true,"profile2":"MVC2019","color":"palegreen","address":7,"isProfileGlobal":true,"profile":"MVC2019","name":"monaco","videoContrastMultiplier":3,"isProfileGlobal2":true},{"videoContrastMultiplier":1,"type":"azul","displayTeensy":"teensy3","color":"black","targetAPKVersion":"5029","address":18,"isProfileGlobal":true,"profile":"MVC2019","name":"newbie","isProfileGlobal2":false,"bootName":"npiSRMHN","isActive":true},{"type":"azul","displayTeensy":"teensy3","color":"black","targetAPKVersion":"5029","address":17,"isProfileGlobal":true,"profile":"MVC2019","name":"newbie","isProfileGlobal2":false,"bootName":"npi3HWBX","isActive":true,"videoContrastMultiplier":1},{"bootName":"pegasus","isActive":true,"profile2":"MVC2019","color":"purple","address":8,"isProfileGlobal":true,"profile":"MVC2019","name":"pegasus","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul"},{"isActive":true,"profile2":"MVC2018","color":"orange","address":10,"isProfileGlobal":true,"profile":"MVC2019","name":"ratchet","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"ratchet"},{"address":11,"isProfileGlobal":true,"profile":"MVC2019","name":"squeeze","videoContrastMultiplier":3,"isProfileGlobal2":true,"type":"azul","bootName":"squeeze","isActive":true,"profile2":"MVC2018","color":"red"},{"videoContrastMultiplier":3,"type":"panel","displayTeensy":"teensy3","color":"steelblue","targetAPKVersion":"5029","address":12,"isProfileGlobal":true,"profile":"MVC2019","name":"supersexy","isProfileGlobal2":false,"bootName":"npiG27AH","isActive":true}]
03-30 03:48:35.055  1924  2267 D BB.AllBoards: A minor change was discovered in Boards JSON.
03-30 03:48:35.059  1924  2267 D BB.AllBoards: No Changes to Boards JSON.
03-30 03:48:36.746  1924  2268 D BB.AllBoards: Address 12
03-30 03:48:36.746  1924  2268 D BB.AllBoards: Board Type panel
03-30 03:48:36.746  1924  2268 D BB.AllBoards: Target APK Version 5029
03-30 03:48:36.747  1924  2268 D BB.AllBoards: videoContrastMultiplier 3
03-30 03:48:36.781  1924  2272 D BB.BBWifi: Check Wifi
03-30 03:48:36.784  1924  2272 D BB.BBWifi: Wifi SSIDs"burnerboard" "burnerboard"
03-30 03:48:36.786  1924  2272 D BB.BBWifi: WIFI IP Address: 10.0.6.198
03-30 03:48:36.796  1924  1924 I BB.BBService: Media file is required to be downloaded before proceeding.  Please hold.
03-30 03:48:38.509  1924  2275 D BB.FileHelpers: Downloading https://us-central1-burner-board.cloudfunctions.net/boards/supersexy/DownloadDirectoryJSON?APKVersion=5029
03-30 03:48:38.510  1924  2275 D BB.MediaManager: Reading Directory from https://us-central1-burner-board.cloudfunctions.net/boards/supersexy/DownloadDirectoryJSON?APKVersion=5029
03-30 03:48:38.513  1924  2275 D BB.MediaManager: Downloaded JSON: {"audio":[{"localName":"VegaMix1.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/VegaMix1.m4a","ordinal":0,"Size":76020326,"Length":3141},{"Length":1219,"localName":"Avener(VeryChill).m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/Avener(VeryChill).m4a","ordinal":1,"Size":30047054},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/FunRideMix.m4a","ordinal":2,"Size":188731798,"Length":7657,"localName":"FunRideMix.m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/CCE-DeepPlayaEve320kbps.m4a","ordinal":3,"Size":111848065,"Length":3452,"localName":"CCE-DeepPlayaEve320kbps.m4a"},{"localName":"Goldcap.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/Goldcap.m4a","ordinal":4,"Size":357105391,"Length":12352},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/TheBoss.m4a","ordinal":5,"Size":36605654,"Length":1485,"localName":"TheBoss.m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/CheeryDayRide(JPOD).m4a","ordinal":6,"Size":105746651,"Length":4291,"localName":"CheeryDayRide(JPOD).m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/VocalChill.m4a","ordinal":7,"Size":81377391,"Length":3302,"localName":"VocalChill.m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/2 Many DJs.m4a","ordinal":8,"Size":93335123,"Length":3787,"localName":"2 Many DJs.m4a"},{"localName":"DanceMix(BenChun).m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/DanceMix(BenChun).m4a","ordinal":9,"Size":72039393,"Length":2923},{"Length":3072,"localName":"CafedelMar(Chillout).m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/CafedelMar(Chillout).m4a","ordinal":10,"Size":75717394},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/RockBallads.m4a","ordinal":11,"Size":114058354,"Length":4628,"localName":"RockBallads.m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/Girl Talk - All Day.m4a","ordinal":12,"Size":105092110,"Length":4264,"localName":"Girl Talk - All Day.m4a"},{"URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/I LOVE the 80's Mix.m4a","ordinal":13,"Size":116406102,"Length":4723,"localName":"I LOVE the 80's Mix.m4a"},{"Length":8662,"localName":"Deep&Sexy.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/Deep&Sexy.m4a","ordinal":14,"Size":286558214},{"ordinal":15,"Size":96974522,"Length":2931,"localName":"HillbillyStep.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/HillbillyStep.m4a"},{"localName":"MyLifeInTheBushOfGhosts.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/MyLifeInTheBushOfGhosts.m4a","ordinal":16,"Size":78880333,"Length":3259},{"localName":"Donna Grantis.m4a","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/Donna Grantis.m4a","ordinal":17,"Size":59210764,"Length":2446}],"video":[{"algorithm":"modeMatrix(kMatrixBurnerColor)","ordinal":0},{"localName":"tunnels.mp4","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/tunnels.mp4","ordinal":1,"Size":95113737},{"ordinal":2,"algorithm":"modePlayaMap()"},{"algorithm":"modeMatrix(kMatrixLunarian)","ordinal":3},{"algorithm":"modeAudioCenter()","ordinal":4},{"ordinal":5,"algorithm":"modeAudioBarV()"},{"ordinal":6,"algorithm":"modeAudioTile()"},{"localName":"fireball2018.mp4","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/fireball2018.mp4","ordinal":7,"Size":14897253},{"localName":"lightrays.mp4","URL":"https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/lightrays.mp4","ordinal":8,"Size
03-30 03:48:38.513  1924  2275 D BB.MediaManager: Found First Media.
03-30 03:48:38.513  1924  2275 D BB.BBService: Text to Speech Null
03-30 03:48:38.516  1924  2275 D BB.BBService: Text to Speech Null
03-30 03:48:38.805  1924  2275 D BB.FileHelpers: Downloading https://storage.googleapis.com/burner-board/BurnerBoardMedia/global/MVC2019/VegaMix1.m4a
03-30 03:48:38.806  1924  2275 D BB.BBService: Text to Speech Null
03-30 03:48:38.806  1924  2275 D BB.MediaManager: Downloading VegaMix1.m4a, 0 Percent
03-30 03:48:38.817  1924  1924 D BB.BurnerBoard: Visualization: Using Panel
03-30 03:48:38.821  1924  1924 D BB.BurnerBoardPanel: Burner Board Panel initting...
03-30 03:48:38.831  1924  1924 D BB.BurnerBoard: BurnerBoard: initUsb()
03-30 03:48:38.837  1924  1924 D BB.BurnerBoard: checking device 0, pid:1155, vid: 5824
03-30 03:48:38.837  1924  1924 D BB.BurnerBoard: found Burnerboard
03-30 03:48:38.841  1924  1924 D BB.BurnerBoard: USB: Connected
03-30 03:48:38.841  1924  1924 D BB.BurnerBoard: Starting io manager ..
03-30 03:48:38.842  1924  1924 D BB.BurnerBoard: USB Connected to supersexy
03-30 03:48:38.845  1924  1924 D BB.BoardVisualization: Starting Board Visualization Burner Board Panel on supersexy
03-30 03:48:38.845  1924  1924 D BB.BoardVisualization: Board framerate set to 12
03-30 03:48:38.846  1924  1924 I BB.BBService: Setting initial visualization mode: 0
03-30 03:48:38.846  1924  1924 D BB.BoardVisualization: Setting visualization mode to: 0
03-30 03:48:38.847  1924  2366 D BB.BoardVisualization: Starting board display thread...
03-30 03:48:38.852  1924  1924 D BB.MusicPlayer: has audio LowLatencyFeature: true
03-30 03:48:38.852  1924  1924 D BB.MusicPlayer: has audio ProFeature: true
03-30 03:48:38.856  1924  1924 D BB.MusicPlayer: audio sampleRate: 44100
03-30 03:48:38.856  1924  1924 D BB.MusicPlayer: audio framesPerBufferInt: 512
03-30 03:48:38.863  1924  1924 D BB.BB.BluetoothConnMgr: Bluetooth packet name set to: supersex
03-30 03:48:38.865  1924  1924 D BB.BB.BluetoothConnMgr: Bluetooth Adapter is already enabled.
03-30 03:48:38.870  1924  1924 D BB.BluetoothLEServer: Bluetooth enabled...starting services
03-30 03:48:38.882  1924  1924 D BB.Gps  : Gps starting
03-30 03:48:38.883  1924  1924 D BB.Gps  : SentenceListener started
03-30 03:48:38.884  1924  1924 D BB.RF   : RF: initUsb()
03-30 03:48:38.886  1924  1937 D BB.BluetoothLEServer: Gattserver onServiceAdded
03-30 03:48:38.887  1924  1924 D BB.RF   : There are 2 drivers
03-30 03:48:38.887  1924  1924 D BB.RF   : checking device 0, pid:1155, vid: 5824
03-30 03:48:38.887  1924  1924 D BB.RF   : checking device 0, pid:32779, vid: 9114
03-30 03:48:38.887  1924  1924 D BB.RF   : Found Adafruit RADIO module
03-30 03:48:38.887  1924  1924 D BB.RF   : found RF
03-30 03:48:38.887  1924  1924 D BB.RF   : checking device 0, pid:32779, vid: 9114
03-30 03:48:38.887  1924  1924 D BB.RF   : Found Adafruit RADIO module
03-30 03:48:38.887  1924  1924 D BB.RF   : found RF
03-30 03:48:38.904  1924  2367 D BB.MusicPlayer: playing file /data/user/0/com.richardmcdougall.bb/files/VegaMix1.m4a
03-30 03:48:38.907  1924  1924 D BB.RF   : USB: Connected
03-30 03:48:38.907  1924  1924 D BB.RF   : Starting io manager ..
03-30 03:48:38.908  1924  1924 D BB.RF   : USB Connected to radio
03-30 03:48:38.908  1924  1924 D BB.RF   : GPS Constructor Completed
03-30 03:48:38.910  1924  1924 D BB.FindMyFriends: Starting FindMyFriends
03-30 03:48:38.911  1924  1937 D BB.BluetoothLEServer: LE Advertising Start
03-30 03:48:38.912  1924  1924 D BB.BatterySupervisor: Enable Battery Monitoring? true
03-30 03:48:38.912  1924  1924 D BB.BatterySupervisor: Enable IoT Reporting? true
03-30 03:48:38.914  1924  1924 I BB.BBService: onStartCommand

**Comment by danielkeithw** [comment]
duplicate Build.Serial
