### ISSUE TITLE
Bluetooth stops on Pegasus

### ISSUE THREAD

**Issue by edfine** [rjmcdougall/BB#244]
Pegasus shows up on BBMobile app after a brain reboot, but shortly later it disconnects and then no longer appears under board search. 

Steps to reproduce:
reboot Pegasus' brain, connect BBMobile app, note that it connects.  Then wait or use the app.

Observed: after around 5 minutes the app disconnects and is no longer seen in the BBMobile scan.

**Comment by danielkeithw** [comment]
problem with dragonboard. Upgrade to nanopi is the only solution.
