### ISSUE TITLE
 If not MQTT registered, board will eventually fill up with  messages and hang

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#29]
New boards can get a giant  backlog of MQTT messages over several weeks which causes app-startup time to become minutes.

**Comment by rjmcdougall** [comment]
Interim get-well fix:

adb shell
$
$ su
# cd /data/data/com.richardmcdougall.bb/files
#

**Comment by rjmcdougall** [comment]
Found this happened on artemis and ratchet when they were off network for one week.

**Comment by lesliefine** [comment]
Gr, @rjmcdougall I need you to close it.
