### ISSUE TITLE
Stop announcing track/mode numbers

### ISSUE THREAD

**Issue by woodsonmartin** [rjmcdougall/BB#33]
It’s annoying to hear each track/mode transition announced. Should we have both a “chatty mode” for debugging and a “performance mode” for actual riding?

**Comment by rjmcdougall** [comment]
@danielkeithw @jclarkcom @ricpruss @Danaskorn : can you comment / vote on this? Remote this feature?

**Comment by rjmcdougall** [comment]
I like this suggestion: if we had a switch in the app we could turn on diagnosis mode. @danielkeithw  do we have a setting page that we could add this to?
