### ISSUE TITLE
People don’t ride them enough

### ISSUE THREAD

**Issue by woodsonmartin** [rjmcdougall/BB#35]
Most of the time the boards just sit there

**Comment by rjmcdougall** [comment]
I'd like to propose a solution here: a scheduled group event.

Option # 1: Santa Cruz

Option # 2: Sonoma

Option # 3: LA

**Comment by woodsonmartin** [comment]
Yeah. Agreed. I vote Sonoma.

**Comment by rjmcdougall** [comment]
Weekend of May 26th? Jonathan's pad?

**Comment by rjmcdougall** [comment]
Jun 9th?
Jun 23rd?

**Comment by lesliefine** [comment]
We can't even find a date for dinner and a chat, let alone a weekend! There are two ways this happens. (1) Declared months in advance. (2) You find 3 people who agree, they say, "This is what we are doing," and hope people follow.

**Comment by danielkeithw** [comment]
Seems fixed!
