### ISSUE TITLE
Move bluetooth-pairing button to a separate screen activated by a settings menu

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#40]
It would be great if we could have a settings menu with screens for various things, including:

- popping up a window for BLE board discovery and pairing
- popping up a window for bluetooth remote pairing
- wifi settings: list and choose ssid
- audio-sync settings: setup audio sync calibration and show stats
- etc,..

This issue is just requesting creating the menu and making 2 new screens for BLE board pairing and bluetooth remote pairing there.

**Comment by danielkeithw** [comment]
Duplicate Issue #45
