### ISSUE TITLE
Create an Audio sync settings page (or have it in a consolidated settings page)

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#50]
I need a few knobs -- and will add the appropriate BLE registers:

button: "Audio Remote Master" - on/off
slider: "Audio sync adjust" - values are +/- 100 in units of 1 millisecond

Stat: string name of time-leader
Stat: Number of boards in sync group

**Comment by danielkeithw** [comment]
@rjmcdougall do you still want MS setting?

**Comment by danielkeithw** [comment]
@rjmcdougall do you still need this?

slider: "Audio sync adjust" - values are +/- 100 in units of 1 millisecond

**Comment by danielkeithw** [comment]
@rjmcdougall do you still need this?

slider: "Audio sync adjust" - values are +/- 100 in units of 1 millisecond
