### ISSUE TITLE
Ingest audio as m4a to allow syncing between boards

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#53]
I'm having quite a bit more successful test cases with sync'ed music now. It really seems the android APIs want to be playing m4a (mp4) music files to make the seek positions accurate.

Short term: Would it be possible to add support for m4a files to the cloud app as audio?

Long term: Can we automatically convert all music upon ingestion using a cloud API like https://cloudconvert.com? I see they have a node interface.

In the interim Audacity does a great job of converting, so I think we can just make a set of sync'ed media that we use for the sync group situations.

**Comment by danielkeithw** [comment]
Added support for m4a files.  Ticket for converting https://github.com/rjmcdougall/BB/issues/72
