### ISSUE TITLE
Ingest of m4a into burnerboard.com calculates length wrong

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#54]
For some reason the length of these files are calculated lower than they should be

**Comment by danielkeithw** [comment]
Note:

https://github.com/nikhilm/node-taglib

**Comment by danielkeithw** [comment]
The module I am Using does not support m4a.  When I pull files from google
drive the length properties are stripped (ahhh APIs) so I need To load into
a buffer and estimate the length.

I should be able to work out m4a support. Lemme check.

Alternatively we don’t really need length.  It’s a lot of work when size
will give us the same thing (change detection)

**Comment by rjmcdougall** [comment]
Length is critical to the music sync. It's what the current playing offset
is calculated from...
