### ISSUE TITLE
Map rezooms with each new signal

### ISSUE THREAD

**Issue by woodsonmartin** [rjmcdougall/BB#61]
When you zoom in on the map, the map keeps zooming back out every few seconds. Maybe because it rezooms with every new gps signal received.

**Comment by rjmcdougall** [comment]
Yes. it would be great if it zoomed automatically the first time only, and then after that it's driven by the user who sets center and zoom levels.

**Comment by danielkeithw** [comment]
I'm adding a toggle you can use to determine if you want the map to auto-zoom.
