### ISSUE TITLE
Vary colors of board listings in board scan results

### ISSUE THREAD

**Issue by woodsonmartin** [rjmcdougall/BB#65]
Each board should have an assigned color. To make it easier to pick a board without being able to read the small type when you are messed up.

**Comment by danielkeithw** [comment]
colors can be changed in the boards entity.

**Comment by danielkeithw** [comment]
![image-1](https://user-images.githubusercontent.com/30708750/42131659-bc933bca-7cd4-11e8-9130-aaf5da8933c6.jpg)

**Comment by woodsonmartin** [comment]
Anyone know why burnerboard website won’t load status report?

**Comment by danielkeithw** [comment]
https://github.com/rjmcdougall/BB/issues/119

Ill check
