### ISSUE TITLE
Find my friends: Only keep/return board locations for 30 mins?

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#67]
Either this, or return the GPS age to the app, and let the app decide what to do with stale entries.

**Comment by danielkeithw** [comment]
The app has minimal (nothing except board name) for persistence between sessions so i would like to return the age to the app.

**Comment by edfine** [comment]
This could be visually encoded with color for quick scanning.

**Comment by danielkeithw** [comment]
![img_5148](https://user-images.githubusercontent.com/30708750/42131196-3fb0be0c-7cca-11e8-9ecb-5ed4e8918497.jpg)

**Comment by danielkeithw** [comment]
Return GMT datetime in minutes from board.
merge results with api response from cloud locations.
determine if boards last ack was over 1 hour ago and make it RED if so.

**Comment by danielkeithw** [comment]
app is backwards compatible with previous BLE location responses.   Those bytes were unused (the altitude).
